"""init

Revision ID: 4b5c46013423
Revises: dd33cb03d01f
Create Date: 2023-11-12 17:27:43.952815

"""

# revision identifiers, used by Alembic.
revision = '4b5c46013423'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
